version: '3.9'
services:
  backend:
    build: ./atypica-backend
    container_name: atypica-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
  frontend:
    build: ./atypica-frontend
    container_name: atypica-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
